In [1]:
#First importing core dependencies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt

In [2]:
#loading the kaggle dataset 
daily_activity = pd.read_csv('/kaggle/input/datasets/arashnic/fitbit/mturkfitbit_export_4.12.16-5.12.16/Fitabase Data 4.12.16-5.12.16/dailyActivity_merged.csv')
sleep_day = pd.read_csv('/kaggle/input/datasets/arashnic/fitbit/mturkfitbit_export_4.12.16-5.12.16/Fitabase Data 4.12.16-5.12.16/sleepDay_merged.csv')

# **Dataset Inspection**
Checking the various data types and shapes of the data sets imported

In [3]:
#Checking the info and shape for daily activity 
daily_activity.info()
daily_activity.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 940 entries, 0 to 939
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Id                        940 non-null    int64
 1   ActivityDate              940 non-null    object
 2   TotalSteps                940 non-null    int64
 3   TotalDistance             940 non-null    float64
 4   TrackerDistance           940 non-null    float64
 5   LoggedActivitiesDistance  940 non-null    float64
 6   VeryActiveDistance        940 non-null    float64
 7   ModeratelyActiveDistance  940 non-null    float64
 8   LightActiveDistance       940 non-null    float64
 9   SedentaryActiveDistance   940 non-null    float64
 10  VeryActiveMinutes         940 non-null    int64
 11  FairlyActiveMinutes       940 non-null    int64
 12  LightlyActiveMinutes      940 non-null    int64
 13  SedentaryMinutes          940 non-null    int64
 14  Calories                  940 non-null    int64
dtypes: float64(7), int64(7), object(1)
memory usage: 110.3+ KB

(940, 15)

In [4]:
#Checking the info and shape for sleep day
sleep_day.info()
sleep_day.describe()
sleep_day.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 413 entries, 0 to 412
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Id                  413 non-null    int64
 1   SleepDay            413 non-null    object
 2   TotalSleepRecords   413 non-null    int64
 3   TotalMinutesAsleep  413 non-null    int64
 4   TotalTimeInBed      413 non-null    int64
dtypes: int64(4), object(1)
memory usage: 16.3+ KB

(413, 5)

> Getting the heads of the datasets

In [5]:
daily_activity.head(10)

,Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories
0,1503960366,4/12/2016,13162,8.50,8.50,0.0,1.88,0.55,6.06,0.0,25,13,328,728,1985
1,1503960366,4/13/2016,10735,6.97,6.97,0.0,1.57,0.69,4.71,0.0,21,19,217,776,1797
2,1503960366,4/14/2016,10460,6.74,6.74,0.0,2.44,0.40,3.91,0.0,30,11,181,1218,1776
3,1503960366,4/15/2016,9762,6.28,6.28,0.0,2.14,1.26,2.83,0.0,29,34,209,726,1745
4,1503960366,4/16/2016,12669,8.16,8.16,0.0,2.71,0.41,5.04,0.0,36,10,221,773,1863
5,1503960366,4/17/2016,9705,6.48,6.48,0.0,3.19,0.78,2.51,0.0,38,20,164,539,1728
6,1503960366,4/18/2016,13019,8.59,8.59,0.0,3.25,0.64,4.71,0.0,42,16,233,1149,1921
7,1503960366,4/19/2016,15506,9.88,9.88,0.0,3.53,1.32,5.03,0.0,50,31,264,775,2035
8,1503960366,4/20/2016,10544,6.68,6.68,0.0,1.96,0.48,4.24,0.0,28,12,205,818,1786
9,1503960366,4/21/2016,9819,6.34,6.34,0.0,1.34,0.35,4.65,0.0,19,8,211,838,1775

In [6]:
sleep_day.head(10)

,Id,SleepDay,TotalSleepRecords,TotalMinutesAsleep,TotalTimeInBed
0,1503960366,4/12/2016 12:00:00 AM,1,327,346
1,1503960366,4/13/2016 12:00:00 AM,2,384,407
2,1503960366,4/15/2016 12:00:00 AM,1,412,442
3,1503960366,4/16/2016 12:00:00 AM,2,340,367
4,1503960366,4/17/2016 12:00:00 AM,1,700,712
5,1503960366,4/19/2016 12:00:00 AM,1,304,320
6,1503960366,4/20/2016 12:00:00 AM,1,360,377
7,1503960366,4/21/2016 12:00:00 AM,1,325,364
8,1503960366,4/23/2016 12:00:00 AM,1,361,384
9,1503960366,4/24/2016 12:00:00 AM,1,430,449

# **Data Checks**:

These data checks are done to check for null and duplicate values, which could cause inaccurate results after the analysis is done

In [7]:
daily_activity.isnull().sum()

Id                          0
ActivityDate                0
TotalSteps                  0
TotalDistance               0
TrackerDistance             0
LoggedActivitiesDistance    0
VeryActiveDistance          0
ModeratelyActiveDistance    0
LightActiveDistance         0
SedentaryActiveDistance     0
VeryActiveMinutes           0
FairlyActiveMinutes         0
LightlyActiveMinutes        0
SedentaryMinutes            0
Calories                    0
dtype: int64

In [8]:
daily_activity.duplicated().sum()

np.int64(0)

In [9]:
sleep_day.isnull().sum()

Id                    0
SleepDay              0
TotalSleepRecords     0
TotalMinutesAsleep    0
TotalTimeInBed        0
dtype: int64

In [10]:
sleep_day.duplicated().sum()

np.int64(3)

> Three duplicates were found in the sleep_day data set, so they need to be handled to prevent problems with the analysis

In [11]:
sleep_day.drop_duplicates()

,Id,SleepDay,TotalSleepRecords,TotalMinutesAsleep,TotalTimeInBed
0,1503960366,4/12/2016 12:00:00 AM,1,327,346
1,1503960366,4/13/2016 12:00:00 AM,2,384,407
2,1503960366,4/15/2016 12:00:00 AM,1,412,442
3,1503960366,4/16/2016 12:00:00 AM,2,340,367
4,1503960366,4/17/2016 12:00:00 AM,1,700,712
...,...,...,...,...,...
408,8792009665,4/30/2016 12:00:00 AM,1,343,360
409,8792009665,5/1/2016 12:00:00 AM,1,503,527
410,8792009665,5/2/2016 12:00:00 AM,1,415,423
411,8792009665,5/3/2016 12:00:00 AM,1,516,545
412,8792009665,5/4/2016 12:00:00 AM,1,439,463

In [12]:
# Converting date and time to date_time objects,
daily_activity['ActivityDate'] = pd.to_datetime(daily_activity['ActivityDate'])
sleep_day['SleepDay'] = pd.to_datetime(sleep_day['SleepDay'])

# normalising the sleep_day to strip the time
sleep_day['SleepDay'] = sleep_day['SleepDay'].dt.normalize()
daily_activity['ActivityDate'] = daily_activity['ActivityDate'].dt.normalize()

/tmp/ipykernel_17/380686461.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  sleep_day['SleepDay'] = pd.to_datetime(sleep_day['SleepDay'])

# **Merging the Data sets**

In [13]:
#Renaming the sleepday date 
sleep_day.rename(columns={"SleepDay": "ActivityDate"},inplace= True)
#Merging the data_sets on the dates using a left join
combined_data = pd.merge(daily_activity, sleep_day, on=['Id', 'ActivityDate'], how='left')
combined_data.head()

,Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories,TotalSleepRecords,TotalMinutesAsleep,TotalTimeInBed
0,1503960366,2016-04-12,13162,8.50,8.50,0.0,1.88,0.55,6.06,0.0,25,13,328,728,1985,1.0,327.0,346.0
1,1503960366,2016-04-13,10735,6.97,6.97,0.0,1.57,0.69,4.71,0.0,21,19,217,776,1797,2.0,384.0,407.0
2,1503960366,2016-04-14,10460,6.74,6.74,0.0,2.44,0.40,3.91,0.0,30,11,181,1218,1776,NaN,NaN,NaN
3,1503960366,2016-04-15,9762,6.28,6.28,0.0,2.14,1.26,2.83,0.0,29,34,209,726,1745,1.0,412.0,442.0
4,1503960366,2016-04-16,12669,8.16,8.16,0.0,2.71,0.41,5.04,0.0,36,10,221,773,1863,2.0,340.0,367.0


> print("Daily Activity Date Example:", daily_activity['ActivityDate'].iloc[0])
> 
> print("Sleep Day Date Example:", sleep_day['ActivityDate'].iloc[0])
> 
> print("Daily Activity Type:", daily_activity['ActivityDate'].dtype)
> 
> print("Sleep Day Type:", sleep_day['ActivityDate'].dtype)
>
> 
 **Check to verify if dates overlapped**

# **Analysis**

In [14]:
# This counts how many rows have activity but NO sleep data
missing_sleep = combined_data['TotalMinutesAsleep'].isnull().sum()
print(f"There are {missing_sleep} days where users tracked activity but not sleep.")

There are 530 days where users tracked activity but not sleep.

In [15]:
#  new dataframe that ONLY contains days where sleep was tracked
sleep_tracked_only = combined_data.dropna(subset=['TotalMinutesAsleep'])

# calculating the average on this filtered dataframe
avg_awake = (sleep_tracked_only['TotalTimeInBed'] - sleep_tracked_only['TotalMinutesAsleep']).mean()

print(f"On days when sleep was tracked, users spent an average of {avg_awake:.2f} minutes awake in bed.")

On days when sleep was tracked, users spent an average of 39.17 minutes awake in bed.

In [16]:
# Calculate average sedentary hours per day
avg_sedentary_h = sleep_tracked_only['SedentaryMinutes'].mean() / 60
print(f"On average, users are sedentary for {avg_sedentary_h:.2f} hours a day.")

On average, users are sedentary for 11.87 hours a day.

In [17]:
# Create a Day of Week column
sleep_tracked_only['DayOfWeek'] = pd.to_datetime(sleep_tracked_only['ActivityDate']).dt.day_name()

# Check average steps by day
day_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
print(sleep_tracked_only.groupby('DayOfWeek')['TotalSteps'].mean().reindex(day_order))

DayOfWeek
Monday       9339.851064
Tuesday      9182.692308
Wednesday    8022.863636
Thursday     8205.353846
Friday       7901.403509
Saturday     9948.689655
Sunday       7297.854545
Name: TotalSteps, dtype: float64

/tmp/ipykernel_17/594998679.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sleep_tracked_only['DayOfWeek'] = pd.to_datetime(sleep_tracked_only['ActivityDate']).dt.day_name()

In [18]:
# Correlation between Steps and Calories
correlation = sleep_tracked_only['TotalSteps'].corr(sleep_tracked_only['Calories'])
print(f"Correlation between Steps and Calories: {correlation:.2f}")

Correlation between Steps and Calories: 0.41

In [19]:
# Calculate Sleep Quality Ratio
sleep_tracked_only['Sleep_Quality_Ratio'] = (sleep_tracked_only['TotalMinutesAsleep'] / sleep_tracked_only['TotalTimeInBed']) * 100

# Average Sleep Quality
avg_quality = sleep_tracked_only['Sleep_Quality_Ratio'].mean()
print(f"Average Sleep Quality: {avg_quality:.2f}%")

Average Sleep Quality: 91.68%

/tmp/ipykernel_17/1702159130.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sleep_tracked_only['Sleep_Quality_Ratio'] = (sleep_tracked_only['TotalMinutesAsleep'] / sleep_tracked_only['TotalTimeInBed']) * 100

# **Exporting Summary Data**

In [20]:
df_for_export = sleep_tracked_only.copy()

# Group by ID and calculate averages
final_summary = df_for_export.groupby('Id').agg({
    'TotalSteps': 'mean',
    'Calories': 'mean',
    'TotalMinutesAsleep': 'mean',
    'TotalTimeInBed': 'mean',
    'SedentaryMinutes': 'mean',
    'Sleep_Quality_Ratio': 'mean'
}).reset_index()

final_summary = final_summary.round(2)

# EXPORT
final_summary.to_csv('bellabeat_final_analysis.csv', index=False)

print("File successfully saved to /kaggle/working/bellabeat_final_analysis.csv")

File successfully saved to /kaggle/working/bellabeat_final_analysis.csv